//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace PBMApp.Model
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class Entities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“Entities”部分中的连接字符串初始化新 Entities 对象。
        /// </summary>
        public Entities() : base("name=Entities", "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 Entities 对象。
        /// </summary>
        public Entities(string connectionString) : base(connectionString, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 Entities 对象。
        /// </summary>
        public Entities(EntityConnection connection) : base(connection, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<WH_Clerk> WH_Clerk
        {
            get
            {
                if ((_WH_Clerk == null))
                {
                    _WH_Clerk = base.CreateObjectSet<WH_Clerk>("WH_Clerk");
                }
                return _WH_Clerk;
            }
        }
        private ObjectSet<WH_Clerk> _WH_Clerk;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<WH_CookInformation> WH_CookInformation
        {
            get
            {
                if ((_WH_CookInformation == null))
                {
                    _WH_CookInformation = base.CreateObjectSet<WH_CookInformation>("WH_CookInformation");
                }
                return _WH_CookInformation;
            }
        }
        private ObjectSet<WH_CookInformation> _WH_CookInformation;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<WH_Department> WH_Department
        {
            get
            {
                if ((_WH_Department == null))
                {
                    _WH_Department = base.CreateObjectSet<WH_Department>("WH_Department");
                }
                return _WH_Department;
            }
        }
        private ObjectSet<WH_Department> _WH_Department;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<WH_Relation_Cook_PLU> WH_Relation_Cook_PLU
        {
            get
            {
                if ((_WH_Relation_Cook_PLU == null))
                {
                    _WH_Relation_Cook_PLU = base.CreateObjectSet<WH_Relation_Cook_PLU>("WH_Relation_Cook_PLU");
                }
                return _WH_Relation_Cook_PLU;
            }
        }
        private ObjectSet<WH_Relation_Cook_PLU> _WH_Relation_Cook_PLU;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<WH_Relation_PLU_Condiment> WH_Relation_PLU_Condiment
        {
            get
            {
                if ((_WH_Relation_PLU_Condiment == null))
                {
                    _WH_Relation_PLU_Condiment = base.CreateObjectSet<WH_Relation_PLU_Condiment>("WH_Relation_PLU_Condiment");
                }
                return _WH_Relation_PLU_Condiment;
            }
        }
        private ObjectSet<WH_Relation_PLU_Condiment> _WH_Relation_PLU_Condiment;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<WH_PLU> WH_PLU
        {
            get
            {
                if ((_WH_PLU == null))
                {
                    _WH_PLU = base.CreateObjectSet<WH_PLU>("WH_PLU");
                }
                return _WH_PLU;
            }
        }
        private ObjectSet<WH_PLU> _WH_PLU;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<WH_PLU_Modifier> WH_PLU_Modifier
        {
            get
            {
                if ((_WH_PLU_Modifier == null))
                {
                    _WH_PLU_Modifier = base.CreateObjectSet<WH_PLU_Modifier>("WH_PLU_Modifier");
                }
                return _WH_PLU_Modifier;
            }
        }
        private ObjectSet<WH_PLU_Modifier> _WH_PLU_Modifier;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 用于向 WH_Clerk EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToWH_Clerk(WH_Clerk wH_Clerk)
        {
            base.AddObject("WH_Clerk", wH_Clerk);
        }
    
        /// <summary>
        /// 用于向 WH_CookInformation EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToWH_CookInformation(WH_CookInformation wH_CookInformation)
        {
            base.AddObject("WH_CookInformation", wH_CookInformation);
        }
    
        /// <summary>
        /// 用于向 WH_Department EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToWH_Department(WH_Department wH_Department)
        {
            base.AddObject("WH_Department", wH_Department);
        }
    
        /// <summary>
        /// 用于向 WH_Relation_Cook_PLU EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToWH_Relation_Cook_PLU(WH_Relation_Cook_PLU wH_Relation_Cook_PLU)
        {
            base.AddObject("WH_Relation_Cook_PLU", wH_Relation_Cook_PLU);
        }
    
        /// <summary>
        /// 用于向 WH_Relation_PLU_Condiment EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToWH_Relation_PLU_Condiment(WH_Relation_PLU_Condiment wH_Relation_PLU_Condiment)
        {
            base.AddObject("WH_Relation_PLU_Condiment", wH_Relation_PLU_Condiment);
        }
    
        /// <summary>
        /// 用于向 WH_PLU EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToWH_PLU(WH_PLU wH_PLU)
        {
            base.AddObject("WH_PLU", wH_PLU);
        }
    
        /// <summary>
        /// 用于向 WH_PLU_Modifier EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToWH_PLU_Modifier(WH_PLU_Modifier wH_PLU_Modifier)
        {
            base.AddObject("WH_PLU_Modifier", wH_PLU_Modifier);
        }

        #endregion
    }
    

    #endregion
    
    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Entities", Name="WH_Clerk")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WH_Clerk : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 WH_Clerk 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        public static WH_Clerk CreateWH_Clerk(global::System.Int64 id)
        {
            WH_Clerk wH_Clerk = new WH_Clerk();
            wH_Clerk.ID = id;
            return wH_Clerk;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String isNum
        {
            get
            {
                return _isNum;
            }
            set
            {
                OnisNumChanging(value);
                ReportPropertyChanging("isNum");
                _isNum = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("isNum");
                OnisNumChanged();
            }
        }
        private global::System.String _isNum;
        partial void OnisNumChanging(global::System.String value);
        partial void OnisNumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SecretCode
        {
            get
            {
                return _SecretCode;
            }
            set
            {
                OnSecretCodeChanging(value);
                ReportPropertyChanging("SecretCode");
                _SecretCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SecretCode");
                OnSecretCodeChanged();
            }
        }
        private global::System.String _SecretCode;
        partial void OnSecretCodeChanging(global::System.String value);
        partial void OnSecretCodeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Limitaions
        {
            get
            {
                return _Limitaions;
            }
            set
            {
                OnLimitaionsChanging(value);
                ReportPropertyChanging("Limitaions");
                _Limitaions = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Limitaions");
                OnLimitaionsChanged();
            }
        }
        private global::System.String _Limitaions;
        partial void OnLimitaionsChanging(global::System.String value);
        partial void OnLimitaionsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String InterruptNo
        {
            get
            {
                return _InterruptNo;
            }
            set
            {
                OnInterruptNoChanging(value);
                ReportPropertyChanging("InterruptNo");
                _InterruptNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("InterruptNo");
                OnInterruptNoChanged();
            }
        }
        private global::System.String _InterruptNo;
        partial void OnInterruptNoChanging(global::System.String value);
        partial void OnInterruptNoChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Entities", Name="WH_CookInformation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WH_CookInformation : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 WH_CookInformation 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        public static WH_CookInformation CreateWH_CookInformation(global::System.Int64 id)
        {
            WH_CookInformation wH_CookInformation = new WH_CookInformation();
            wH_CookInformation.ID = id;
            return wH_CookInformation;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Num
        {
            get
            {
                return _Num;
            }
            set
            {
                OnNumChanging(value);
                ReportPropertyChanging("Num");
                _Num = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Num");
                OnNumChanged();
            }
        }
        private Nullable<global::System.Int64> _Num;
        partial void OnNumChanging(Nullable<global::System.Int64> value);
        partial void OnNumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> price
        {
            get
            {
                return _price;
            }
            set
            {
                OnpriceChanging(value);
                ReportPropertyChanging("price");
                _price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("price");
                OnpriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _price;
        partial void OnpriceChanging(Nullable<global::System.Decimal> value);
        partial void OnpriceChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Entities", Name="WH_Department")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WH_Department : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 WH_Department 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        public static WH_Department CreateWH_Department(global::System.Int64 id)
        {
            WH_Department wH_Department = new WH_Department();
            wH_Department.ID = id;
            return wH_Department;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> High_Digit_LockOut
        {
            get
            {
                return _High_Digit_LockOut;
            }
            set
            {
                OnHigh_Digit_LockOutChanging(value);
                ReportPropertyChanging("High_Digit_LockOut");
                _High_Digit_LockOut = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("High_Digit_LockOut");
                OnHigh_Digit_LockOutChanged();
            }
        }
        private Nullable<global::System.Int64> _High_Digit_LockOut;
        partial void OnHigh_Digit_LockOutChanging(Nullable<global::System.Int64> value);
        partial void OnHigh_Digit_LockOutChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> isDirectSale
        {
            get
            {
                return _isDirectSale;
            }
            set
            {
                OnisDirectSaleChanging(value);
                ReportPropertyChanging("isDirectSale");
                _isDirectSale = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isDirectSale");
                OnisDirectSaleChanged();
            }
        }
        private Nullable<global::System.Int64> _isDirectSale;
        partial void OnisDirectSaleChanging(Nullable<global::System.Int64> value);
        partial void OnisDirectSaleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> isAge
        {
            get
            {
                return _isAge;
            }
            set
            {
                OnisAgeChanging(value);
                ReportPropertyChanging("isAge");
                _isAge = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isAge");
                OnisAgeChanged();
            }
        }
        private Nullable<global::System.Int64> _isAge;
        partial void OnisAgeChanging(Nullable<global::System.Int64> value);
        partial void OnisAgeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> isPrice
        {
            get
            {
                return _isPrice;
            }
            set
            {
                OnisPriceChanging(value);
                ReportPropertyChanging("isPrice");
                _isPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isPrice");
                OnisPriceChanged();
            }
        }
        private Nullable<global::System.Int64> _isPrice;
        partial void OnisPriceChanging(Nullable<global::System.Int64> value);
        partial void OnisPriceChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> DepartmentGroup
        {
            get
            {
                return _DepartmentGroup;
            }
            set
            {
                OnDepartmentGroupChanging(value);
                ReportPropertyChanging("DepartmentGroup");
                _DepartmentGroup = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DepartmentGroup");
                OnDepartmentGroupChanged();
            }
        }
        private Nullable<global::System.Int64> _DepartmentGroup;
        partial void OnDepartmentGroupChanging(Nullable<global::System.Int64> value);
        partial void OnDepartmentGroupChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> KP
        {
            get
            {
                return _KP;
            }
            set
            {
                OnKPChanging(value);
                ReportPropertyChanging("KP");
                _KP = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("KP");
                OnKPChanged();
            }
        }
        private Nullable<global::System.Int64> _KP;
        partial void OnKPChanging(Nullable<global::System.Int64> value);
        partial void OnKPChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> isMode
        {
            get
            {
                return _isMode;
            }
            set
            {
                OnisModeChanging(value);
                ReportPropertyChanging("isMode");
                _isMode = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isMode");
                OnisModeChanged();
            }
        }
        private Nullable<global::System.Int64> _isMode;
        partial void OnisModeChanging(Nullable<global::System.Int64> value);
        partial void OnisModeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> isPriceFormat
        {
            get
            {
                return _isPriceFormat;
            }
            set
            {
                OnisPriceFormatChanging(value);
                ReportPropertyChanging("isPriceFormat");
                _isPriceFormat = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isPriceFormat");
                OnisPriceFormatChanged();
            }
        }
        private Nullable<global::System.Int64> _isPriceFormat;
        partial void OnisPriceFormatChanging(Nullable<global::System.Int64> value);
        partial void OnisPriceFormatChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> KP_receipt
        {
            get
            {
                return _KP_receipt;
            }
            set
            {
                OnKP_receiptChanging(value);
                ReportPropertyChanging("KP_receipt");
                _KP_receipt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("KP_receipt");
                OnKP_receiptChanged();
            }
        }
        private Nullable<global::System.Int64> _KP_receipt;
        partial void OnKP_receiptChanging(Nullable<global::System.Int64> value);
        partial void OnKP_receiptChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> isType
        {
            get
            {
                return _isType;
            }
            set
            {
                OnisTypeChanging(value);
                ReportPropertyChanging("isType");
                _isType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isType");
                OnisTypeChanged();
            }
        }
        private Nullable<global::System.Int64> _isType;
        partial void OnisTypeChanging(Nullable<global::System.Int64> value);
        partial void OnisTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> isVat_Tax_GST
        {
            get
            {
                return _isVat_Tax_GST;
            }
            set
            {
                OnisVat_Tax_GSTChanging(value);
                ReportPropertyChanging("isVat_Tax_GST");
                _isVat_Tax_GST = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isVat_Tax_GST");
                OnisVat_Tax_GSTChanged();
            }
        }
        private Nullable<global::System.Int64> _isVat_Tax_GST;
        partial void OnisVat_Tax_GSTChanging(Nullable<global::System.Int64> value);
        partial void OnisVat_Tax_GSTChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String str_Vat_Tax_GST
        {
            get
            {
                return _str_Vat_Tax_GST;
            }
            set
            {
                Onstr_Vat_Tax_GSTChanging(value);
                ReportPropertyChanging("str_Vat_Tax_GST");
                _str_Vat_Tax_GST = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("str_Vat_Tax_GST");
                Onstr_Vat_Tax_GSTChanged();
            }
        }
        private global::System.String _str_Vat_Tax_GST;
        partial void Onstr_Vat_Tax_GSTChanging(global::System.String value);
        partial void Onstr_Vat_Tax_GSTChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Entities", Name="WH_PLU")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WH_PLU : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 WH_PLU 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        public static WH_PLU CreateWH_PLU(global::System.Int64 id)
        {
            WH_PLU wH_PLU = new WH_PLU();
            wH_PLU.ID = id;
            return wH_PLU;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Bar_Code
        {
            get
            {
                return _Bar_Code;
            }
            set
            {
                OnBar_CodeChanging(value);
                ReportPropertyChanging("Bar_Code");
                _Bar_Code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Bar_Code");
                OnBar_CodeChanged();
            }
        }
        private global::System.String _Bar_Code;
        partial void OnBar_CodeChanging(global::System.String value);
        partial void OnBar_CodeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Dept_No
        {
            get
            {
                return _Dept_No;
            }
            set
            {
                OnDept_NoChanging(value);
                ReportPropertyChanging("Dept_No");
                _Dept_No = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Dept_No");
                OnDept_NoChanged();
            }
        }
        private global::System.String _Dept_No;
        partial void OnDept_NoChanging(global::System.String value);
        partial void OnDept_NoChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Price1
        {
            get
            {
                return _Price1;
            }
            set
            {
                OnPrice1Changing(value);
                ReportPropertyChanging("Price1");
                _Price1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price1");
                OnPrice1Changed();
            }
        }
        private Nullable<global::System.Decimal> _Price1;
        partial void OnPrice1Changing(Nullable<global::System.Decimal> value);
        partial void OnPrice1Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Price2
        {
            get
            {
                return _Price2;
            }
            set
            {
                OnPrice2Changing(value);
                ReportPropertyChanging("Price2");
                _Price2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price2");
                OnPrice2Changed();
            }
        }
        private Nullable<global::System.Decimal> _Price2;
        partial void OnPrice2Changing(Nullable<global::System.Decimal> value);
        partial void OnPrice2Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Price3
        {
            get
            {
                return _Price3;
            }
            set
            {
                OnPrice3Changing(value);
                ReportPropertyChanging("Price3");
                _Price3 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price3");
                OnPrice3Changed();
            }
        }
        private Nullable<global::System.Decimal> _Price3;
        partial void OnPrice3Changing(Nullable<global::System.Decimal> value);
        partial void OnPrice3Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> PriceMat
        {
            get
            {
                return _PriceMat;
            }
            set
            {
                OnPriceMatChanging(value);
                ReportPropertyChanging("PriceMat");
                _PriceMat = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PriceMat");
                OnPriceMatChanged();
            }
        }
        private Nullable<global::System.Int64> _PriceMat;
        partial void OnPriceMatChanging(Nullable<global::System.Int64> value);
        partial void OnPriceMatChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> isMode
        {
            get
            {
                return _isMode;
            }
            set
            {
                OnisModeChanging(value);
                ReportPropertyChanging("isMode");
                _isMode = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isMode");
                OnisModeChanged();
            }
        }
        private Nullable<global::System.Int64> _isMode;
        partial void OnisModeChanging(Nullable<global::System.Int64> value);
        partial void OnisModeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Inventory
        {
            get
            {
                return _Inventory;
            }
            set
            {
                OnInventoryChanging(value);
                ReportPropertyChanging("Inventory");
                _Inventory = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Inventory");
                OnInventoryChanged();
            }
        }
        private Nullable<global::System.Int64> _Inventory;
        partial void OnInventoryChanging(Nullable<global::System.Int64> value);
        partial void OnInventoryChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Inventory_safty
        {
            get
            {
                return _Inventory_safty;
            }
            set
            {
                OnInventory_saftyChanging(value);
                ReportPropertyChanging("Inventory_safty");
                _Inventory_safty = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Inventory_safty");
                OnInventory_saftyChanged();
            }
        }
        private Nullable<global::System.Int64> _Inventory_safty;
        partial void OnInventory_saftyChanging(Nullable<global::System.Int64> value);
        partial void OnInventory_saftyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> menu_flag
        {
            get
            {
                return _menu_flag;
            }
            set
            {
                Onmenu_flagChanging(value);
                ReportPropertyChanging("menu_flag");
                _menu_flag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("menu_flag");
                Onmenu_flagChanged();
            }
        }
        private Nullable<global::System.Int64> _menu_flag;
        partial void Onmenu_flagChanging(Nullable<global::System.Int64> value);
        partial void Onmenu_flagChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> isCondiment
        {
            get
            {
                return _isCondiment;
            }
            set
            {
                OnisCondimentChanging(value);
                ReportPropertyChanging("isCondiment");
                _isCondiment = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isCondiment");
                OnisCondimentChanged();
            }
        }
        private Nullable<global::System.Int64> _isCondiment;
        partial void OnisCondimentChanging(Nullable<global::System.Int64> value);
        partial void OnisCondimentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Modifier
        {
            get
            {
                return _Modifier;
            }
            set
            {
                OnModifierChanging(value);
                ReportPropertyChanging("Modifier");
                _Modifier = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Modifier");
                OnModifierChanged();
            }
        }
        private Nullable<global::System.Int64> _Modifier;
        partial void OnModifierChanging(Nullable<global::System.Int64> value);
        partial void OnModifierChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Modifier_description
        {
            get
            {
                return _Modifier_description;
            }
            set
            {
                OnModifier_descriptionChanging(value);
                ReportPropertyChanging("Modifier_description");
                _Modifier_description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Modifier_description");
                OnModifier_descriptionChanged();
            }
        }
        private global::System.String _Modifier_description;
        partial void OnModifier_descriptionChanging(global::System.String value);
        partial void OnModifier_descriptionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Modifier_Unity_Quantity
        {
            get
            {
                return _Modifier_Unity_Quantity;
            }
            set
            {
                OnModifier_Unity_QuantityChanging(value);
                ReportPropertyChanging("Modifier_Unity_Quantity");
                _Modifier_Unity_Quantity = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Modifier_Unity_Quantity");
                OnModifier_Unity_QuantityChanged();
            }
        }
        private global::System.String _Modifier_Unity_Quantity;
        partial void OnModifier_Unity_QuantityChanging(global::System.String value);
        partial void OnModifier_Unity_QuantityChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Modifier_Price
        {
            get
            {
                return _Modifier_Price;
            }
            set
            {
                OnModifier_PriceChanging(value);
                ReportPropertyChanging("Modifier_Price");
                _Modifier_Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Modifier_Price");
                OnModifier_PriceChanged();
            }
        }
        private Nullable<global::System.Int64> _Modifier_Price;
        partial void OnModifier_PriceChanging(Nullable<global::System.Int64> value);
        partial void OnModifier_PriceChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Entities", Name="WH_PLU_Modifier")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WH_PLU_Modifier : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 WH_PLU_Modifier 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        public static WH_PLU_Modifier CreateWH_PLU_Modifier(global::System.Int64 id)
        {
            WH_PLU_Modifier wH_PLU_Modifier = new WH_PLU_Modifier();
            wH_PLU_Modifier.ID = id;
            return wH_PLU_Modifier;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> PLUID
        {
            get
            {
                return _PLUID;
            }
            set
            {
                OnPLUIDChanging(value);
                ReportPropertyChanging("PLUID");
                _PLUID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PLUID");
                OnPLUIDChanged();
            }
        }
        private Nullable<global::System.Int64> _PLUID;
        partial void OnPLUIDChanging(Nullable<global::System.Int64> value);
        partial void OnPLUIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Modifier_desc
        {
            get
            {
                return _Modifier_desc;
            }
            set
            {
                OnModifier_descChanging(value);
                ReportPropertyChanging("Modifier_desc");
                _Modifier_desc = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Modifier_desc");
                OnModifier_descChanged();
            }
        }
        private global::System.String _Modifier_desc;
        partial void OnModifier_descChanging(global::System.String value);
        partial void OnModifier_descChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Modifier_Unit_Quantity
        {
            get
            {
                return _Modifier_Unit_Quantity;
            }
            set
            {
                OnModifier_Unit_QuantityChanging(value);
                ReportPropertyChanging("Modifier_Unit_Quantity");
                _Modifier_Unit_Quantity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Modifier_Unit_Quantity");
                OnModifier_Unit_QuantityChanged();
            }
        }
        private Nullable<global::System.Int64> _Modifier_Unit_Quantity;
        partial void OnModifier_Unit_QuantityChanging(Nullable<global::System.Int64> value);
        partial void OnModifier_Unit_QuantityChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Modifier_Price
        {
            get
            {
                return _Modifier_Price;
            }
            set
            {
                OnModifier_PriceChanging(value);
                ReportPropertyChanging("Modifier_Price");
                _Modifier_Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Modifier_Price");
                OnModifier_PriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _Modifier_Price;
        partial void OnModifier_PriceChanging(Nullable<global::System.Decimal> value);
        partial void OnModifier_PriceChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Entities", Name="WH_Relation_Cook_PLU")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WH_Relation_Cook_PLU : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 WH_Relation_Cook_PLU 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        public static WH_Relation_Cook_PLU CreateWH_Relation_Cook_PLU(global::System.Int64 id)
        {
            WH_Relation_Cook_PLU wH_Relation_Cook_PLU = new WH_Relation_Cook_PLU();
            wH_Relation_Cook_PLU.ID = id;
            return wH_Relation_Cook_PLU;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> CookID
        {
            get
            {
                return _CookID;
            }
            set
            {
                OnCookIDChanging(value);
                ReportPropertyChanging("CookID");
                _CookID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CookID");
                OnCookIDChanged();
            }
        }
        private Nullable<global::System.Int64> _CookID;
        partial void OnCookIDChanging(Nullable<global::System.Int64> value);
        partial void OnCookIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> PLUID
        {
            get
            {
                return _PLUID;
            }
            set
            {
                OnPLUIDChanging(value);
                ReportPropertyChanging("PLUID");
                _PLUID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PLUID");
                OnPLUIDChanged();
            }
        }
        private Nullable<global::System.Int64> _PLUID;
        partial void OnPLUIDChanging(Nullable<global::System.Int64> value);
        partial void OnPLUIDChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Entities", Name="WH_Relation_PLU_Condiment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WH_Relation_PLU_Condiment : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 WH_Relation_PLU_Condiment 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        public static WH_Relation_PLU_Condiment CreateWH_Relation_PLU_Condiment(global::System.Int64 id)
        {
            WH_Relation_PLU_Condiment wH_Relation_PLU_Condiment = new WH_Relation_PLU_Condiment();
            wH_Relation_PLU_Condiment.ID = id;
            return wH_Relation_PLU_Condiment;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> PLUID
        {
            get
            {
                return _PLUID;
            }
            set
            {
                OnPLUIDChanging(value);
                ReportPropertyChanging("PLUID");
                _PLUID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PLUID");
                OnPLUIDChanged();
            }
        }
        private Nullable<global::System.Int64> _PLUID;
        partial void OnPLUIDChanging(Nullable<global::System.Int64> value);
        partial void OnPLUIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> condimentPLUID
        {
            get
            {
                return _condimentPLUID;
            }
            set
            {
                OncondimentPLUIDChanging(value);
                ReportPropertyChanging("condimentPLUID");
                _condimentPLUID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("condimentPLUID");
                OncondimentPLUIDChanged();
            }
        }
        private Nullable<global::System.Int64> _condimentPLUID;
        partial void OncondimentPLUIDChanging(Nullable<global::System.Int64> value);
        partial void OncondimentPLUIDChanged();

        #endregion
    
    }

    #endregion
    
}
